# fly.toml app configuration file generated for breaking-apns-rust-new-billowing-dream-6818 on 2025-11-15T18:54:30+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'breaking-apns-rust-new-billowing-dream-6818'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 8080
    handlers = ['http']

    [services.ports.http_options]
      idle_timeout = 30

[checks]
  [checks.stats]
    port = 8080
    type = 'http'
    interval = '30m0s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/stats'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 2
