app = 'breaking-apns-rust'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 9090
  auto_stop_machines = 'stop'
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 9090
  auto_stop_machines = 'stop'
  auto_start_machines = true
  force_https = true
  soft_limit = 1
  hard_limit = 2
  min_machines_running = 0

  [[services.ports]]
    port = 9090
    handlers = ['http']
    soft_limit = 1
    hard_limit = 2
    [services.ports.http_options]
      idle_timeout = 30

[[vm]]
  memory = '1536mb'
  cpu_kind = 'shared'
  cpus = 1
