GET https://breaking.apns.iavian.net/push/ios/breaking?newsId=412888&dhash=7C0D8F39-BE16-4994-9BCE-B0ED023646B6

###
GET http://localhost:8080/stats

###
GET http://localhost:8080/push/ios/breaking?db_partitiwon=1&newsId=404147&dhash=7C0D8F39-BE16-4994-9BCE-B0ED023646B6

###
GET https://breaking.apns.iavian.net/push/ios/breaking?newsId=411265

###
GET https://breaking.apns.iavian.net/stats
